using './main.bicep'

param workloadName = 'openmrs'
param environmentName = 'prod'
param imageRepository = 'openmrs-core'
param imageTag = 'latest'
param dbAdminUsername = 'openmrsadmin'
param dbName = 'openmrs'
param databaseEngine = 'MySQL'
param vnetAddressPrefix = '10.0.0.0/16'
param acaSubnetPrefix = '10.0.0.0/23'
param appGatewaySubnetPrefix = '10.0.2.0/24'
param dbSubnetPrefix = '10.0.3.0/24'
param mgmtSubnetPrefix = '10.0.4.0/24'
